name: Compliment Generator

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  generate-compliment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - name: Install dependencies
        run: npm ci

      - name: Build the action 
        run: npm run build

      - name: Remove node_modules
        run: rm -rf node_modules
        
      - name: Run Compliment Generator with Compliment Bot Action
        uses: ./
        with:
          developer_name: 'Super Developer'
          compliment_style: 'motivational'

      - name: Run Compliment Generator with Compliment Bot Action
        uses: junjie-w/compliment-bot-action@v1.1.0
        with:
          developer_name: 'Code Wizard'
          compliment_style: 'funny'
          